-- Oracle Database Table Creation Script for Transactions
-- Run this script in Oracle SQL*Plus or SQL Developer if the table doesn't exist

CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID VARCHAR2(64) PRIMARY KEY,
    TIMESTAMP_VAL TIMESTAMP DEFAULT SYSTIMESTAMP,
    CURRENCY VARCHAR2(10) NOT NULL,
    AMOUNT NUMBER(18,2) NOT NULL,
    SENDER_ACCOUNT VARCHAR2(50) NOT NULL,
    RECEIVER_ACCOUNT VARCHAR2(50) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(20),
    CHANNEL VARCHAR2(20),
    STATUS VARCHAR2(20),
    IP_ADDRESS VARCHAR2(15),
    LOCATION VARCHAR2(50),
    FRAUD_FLAG NUMBER(1) DEFAULT 0,
    FRAUD_REASON VARCHAR2(500),
    ML_SCORE NUMBER(5,4) DEFAULT 0.0
);

-- Optional: Create an index on timestamp for faster queries
CREATE INDEX IDX_TRANSACTIONS_TIMESTAMP ON TRANSACTIONS(TIMESTAMP_VAL);

-- Verify table creation
SELECT * FROM TRANSACTIONS;

-- If table already exists, add ML_SCORE column:
-- ALTER TABLE TRANSACTIONS ADD ML_SCORE NUMBER(5,4) DEFAULT 0.0;

